language: node_js
node_js:
  - "node" # latest stable Node.js release
  - "lts/*" # latest LTS Node.js release
  - "18" # specific version
install: npm install
services:
  - postgresql
  before_script:
  - psql -c 'create database test;' -U postgres
script: npm test
after_success: npm run coverage